-- CRIAR NOVO DB
CREATE DATABASE GREENHOUSE;

-- UTILIZANDO O DB
USE GREENHOUSE;

-- CRIANDO UMA TABELA
CREATE TABLE `GREENHOUSE`.`PLANTS`(
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL
    DEFAULT CURRENT_TIMESTAMP ON 
    UPDATE CURRENT_TIMESTAMP,
    `SENSOR_LEVEL` CHAR(5) DEFAULT NULL,
    PRIMARY KEY `PK_PLANT_NAME` (`PLANT_NAME`)
);

-- COMANDOS DML DE INSERÇÃO DE DADOS
INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Orquidea', 10, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Canhamo', 420, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Pinheiro', 25, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Girassol', 2, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Violeta', 666, 'MED');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Mandioca', 51, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Cacto', 15, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Figueira', 30, 'MED');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Samambaia', 40, 'MED');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Roseira', 18, 'LOW');

SELECT * FROM `GREENHOUSE`.`PLANTS`;

-- ESPECIFICANDO APENAS AS COLUNAS DESEJADAS
SELECT `PLANT_NAME`, `SENSOR_EVENT`
FROM `GREENHOUSE`.`PLANTS`;

-- Aplicar filtros nos registros de dados

SELECT * FROM PLANTS
WHERE SENSOR_LEVEL = 'HIGH'
AND SENSOR_VALUE >= '10' AND SENSOR_VALUE <= 20;

SELECT * FROM PLANTS
WHERE SENSOR_LEVEL IN ('HIGH', 'LOW');

-- CLAUSULA DE ORDENAÇÃO
SELECT * FROM PLANTS
WHERE SENSOR_VALUE < 420
ORDER BY SENSOR_VALUE DESC;

-- FUNÇÕES DE AGRUPAMENTO
SELECT COUNT(*), SENSOR_LEVEL
FROM PLANTS
GROUP BY SENSOR_LEVEL;

SELECT *
FROM PLANTS
LIMIT 3;

SELECT MIN(SENSOR_VALUE) AS MIN_VALUE
FROM PLANTS;

SELECT MAX(SENSOR_VALUE) AS MAX_VALUE
FROM PLANTS;

SELECT SUM(SENSOR_VALUE)
FROM PLANTS
WHERE SENSOR_LEVEL = 'HIGH';

SELECT AVG(SENSOR_VALUE)
FROM PLANTS;

-- Comando update para atualizar registro de dados

SELECT * FROM PLANTS;

UPDATE PLANTS
SET SENSOR_VALUE = 90, SENSOR_LEVEL = 'HIGH'
WHERE PLANT_NAME = 'Roseira';

-- Apagando registro da tabela do banco de dados
DELETE FROM PLANTS
WHERE PLANT_NAME = 'Figueira';